'use client';

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { initSystemStatus } from './lib/systemStatus'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Arbitrage Arbitrage System',
    description: 'Generated by Agent',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    initSystemStatus(() => {
        document.body.setAttribute('data-system', 'ready');
    });

    return (
        <html lang="en" className="dark">
            <head>
                <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
            </head>
            <body className={inter.className}>{children}</body>
        </html>
    )
}
