import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SystemBootstrap from './providers';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Arbitrage Arbitrage System',
    description: 'Generated by Agent',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SystemBootstrap>
                    {children}
                </SystemBootstrap>
            </body>
        </html>
    )
}
